Pin GitHub CI Rust toolchain to 1.93.0
Using the floating stable toolchain currently breaks this project. Repro via just build-debug:

```
Compiling matrix-sdk v0.16.0
error: queries overflow the depth limit!
help: consider increasing the recursion limit by adding #![recursion_limit = "256"] to your crate (matrix_sdk)
note: query depth increased by 130 when computing layout of matrix-sdk Client::sync async body
error: could not compile matrix-sdk (lib) due to 1 previous error
```

Pinning CI to 1.93.0 keeps CI on the known-good toolchain until upstream/toolchain compatibility is addressed.
We should have had that to begin with (we're pinning as much as we can anyway), but..

Ref: https://github.com/etkecc/baibot/pull/83#issuecomment-4008463792